apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: checkout-demo
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'gateway'
        metrics_path: /metrics
        static_configs:
          - targets: ['gateway:80']

      - job_name: 'checkout'
        metrics_path: /metrics
        static_configs:
          - targets: ['checkout:8003']

      - job_name: 'pricing'
        metrics_path: /metrics
        static_configs:
          - targets: ['pricing:8001']

      - job_name: 'inventory'
        metrics_path: /metrics
        static_configs:
          - targets: ['inventory:8002']
